# Оставил строки для логгирования, JWT и других параметров в комментариях, вы можете их раскомментировать и настроить по необходимости

#logging:
#  level:
#    org: DEBUG
#    com: DEBUG
#jwt:
#  secret:
#    access: "Tokens"
#    refresh: "Tokens"

server:
  port: 9000

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  security:
    enable: true

---

# Настройки для профиля local

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      settings:
        trace: on
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: none

---

# Настройки для профиля prod
# Нужно указать url, password, user для дб

spring:
  profiles:
     active: local
  datasource:
    url: jdbc:postgresql://hattie.db.elephantsql.com:5432/kksoceqt
    username: kksoceqt
    password: SuewuMYeqUD8rVgmtQlrpvieFCrDVe3A
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
